services:
  wwii-soldier-surveys:
    image: bdtrippdev/wwii-soldier-surveys:${TAG}
    restart: always
    labels:
      - "deunhealth.restart=true"
    environment:
      - VIRTUAL_HOST=${FQDN}
      - ENV_NAME=${ENV_NAME}
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - public_net
networks:
  public_net:
    name: ${ENV_NAME}_public
    external: true
    