on:
  push:
    #Does not run until the merge happens
    branches:
      - dev
      - master
jobs:
  build-for-dev:
    if: github.ref == 'refs/heads/dev'
    uses: bdtripp-dev/infra-proxy-stack/.github/workflows/reusable-docker-build-and-push.yaml@dev
    with:
      image_name: "wwii-soldier-surveys"     # This is passed to the template
      dockerfile_path: "./Dockerfile" # This is passed to the template
    secrets: inherit  # Passes necessary registry credentials securely
  build-for-production:
    if: github.ref == 'refs/heads/master'
    uses: bdtripp-dev/infra-proxy-stack/.github/workflows/reusable-docker-build-and-push.yaml@master
    with:
      image_name: "wwii-soldier-surveys"     # This is passed to the template
      dockerfile_path: "./Dockerfile" # This is passed to the template
    secrets: inherit  # Passes necessary registry credentials securely
